[package]
name = "example3"
version = "0.1.0"
authors = ["Razican <razican@protonmail.ch>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

[dependencies.chrono]
version = "0.4.0"
features = ["serde"]
