[package]
name = "web_bank"
version = "0.1.0"
authors = ["storyfeet <thebeaky@psmail.net>"]
edition = "2018"

[dependencies]
minibankdb = {path = "../../day6/add_03-04/"}
rand = "0.5.5"
maud = "0.19.0"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
serde = "1.0"
serde_derive="1.0"
