[package]
name = "router-microservice"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
config = "0.9"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"
