[package]
name = "user-location"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.32"
failure = "0.1"
rusoto_core = "0.36.0"
rusoto_dynamodb = "0.36.0"
