[package]
name = "actors"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
syslog = "4.0"
queryst = "2.0"
image = "0.20"
