[package]
name = "random-service-with-env"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.5"
dotenv = "0.13"
hyper = "0.12"
rand = "0.5"
